### PR TITLE
update to 6.2.25

### PR DESCRIPTION
**Pull request by margaale**
I know it not ideal, but while you figure how update whe a new version is out i leave you this PR

### CODE REVIEW

**Comment by jacobalberty** [comment]
This RC appears to still be in early access, to comply with the ubiquiti early access tos it is preferable to pass the beta package in the PKGURL environment variable to `jacobalberty/unifi:beta` instead of having a tagged release for it.

**Comment by margaale** [comment]
Just went out to RC: https://community.ui.com/releases/UniFi-Network-Application-6-2-23/df89533b-184a-4fb7-b2c6-9f894b82df27

**Comment by cton** [comment]
it is now promoted to be stable

**Comment by bruvv** [comment]
Already pushed: https://github.com/jacobalberty/unifi-docker/commit/6d9c8510232a888a4d536e1be2605950d3f64b79 @margaale  this can be closed.

**Pull request closed without merging**
