### PR TITLE
corrected issue with and simplified jsvc stop command and added warning

### PR DESCRIPTION
**Pull request by JPvRiel**
There was a bug with the stop command.

I've now tested and fixed it and dealt with the case where processes end within a container, instead of being signaled to terminate. I figured that warranted a warning on stderr.

### CODE REVIEW

**Comment by jacobalberty** [comment]
This appears to just contain an update to readme.md regarding timezones?

**Comment by jacobalberty** [comment]
Aha I figured out why, you forgot to check in unifi.sh I'm reverting the previous pull request temporarily till we can get build working.

**Comment by JPvRiel** [comment]
Hi, apologies, seems I've caused a conflict in the README file.

I also put in a lengthy separate `deb_package_review.md` which should help anyone wanting to work on and improve the the docker image for v5.

**Comment by jacobalberty** [comment]
The conflict is because I backed out the last PR. When I reapply it the
readme. MD conflict will resolve itself

**Comment by jacobalberty** [comment]
This doesnt apply anymore to the current build system.

**Pull request closed without merging**
