### PR TITLE
[TASK] Updated the workflows

### PR DESCRIPTION
**Pull request by GoliathLabs**
Use a prefix like [TASK], [BUGFIX], [DOC] or [CGL] and provide a general summary of your changes in the Title above.

*Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.*

Please provide enough information so that others can review your pull request:
I've added two distinct workflows which replace the ci workflow. Images will be build when a PR get's created. This will be cached. If the PR get's merged, the cache can be used for a faster push to the registry.

## Description
Explain the **details** for making this change. What existing problem does the pull request solve?
Currently the PRs are failing as the workflow is configured to automatically push to the registry if it's not a PR. If it is a PR, it fails. That's what I'm trying to fix with this PR.

## Motivation and Context
Why is this change required? What problem does it solve?
See above explanation.

## Checklist:
Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!
- [X] My code follows the code style of this project. (CI will test it anyway and also needs approval)
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by GoliathLabs** [comment]
@jacobalberty we might want to look into the build issues (https://github.com/docker/buildx/issues/290)

**Comment by jacobalberty** [comment]
@GoliathLabs Is it related to that issue or is it because the docker login action was removed from build.yml?

**Comment by GoliathLabs** [comment]
@jacobalberty it isn't related to the removed docker login action as we want gh-actions to try to build the image. The login action is in the docker.yml which pushes the image to the registry.

Therefore we have to work around the issue (see the link in my post above).

**Comment by jacobalberty** [comment]
Looking at it it looks like i just need to set load: false it looks like the cache-to: gha will take the resulting image won't it to cache for the docker.yml or am i missing something?

**Comment by jacobalberty** [comment]
github actions is giving me
```
Invalid workflow file : .github/workflows/docker.yml#L11
You have an error in your yaml syntax on line 11
```
But my eyes (and multiple linters) aren't seeing anything do you see anything @GoliathLabs ?

**Comment by jacobalberty** [comment]
ok figured it out was missing a build: and runs-on: line. I believe the load parameter being set to false has the other issue fixed too.

**Comment by GoliathLabs** [comment]
@jacobalberty sorry, haven't noticed the email notifications. I'm glad you figured it out though!

**Comment by GoliathLabs** [comment]
But it looks like it still ain't happy

**Comment by jacobalberty** [comment]
docker/build-push-action#515 Looks like its a github issue. The failure should be a warning not an error and github action cache is having issues. It's actually pushing the images to docker hub fine, it's just not caching pull requests and it's erroneously reporting an error on all builds.

**Comment by jacobalberty** [comment]
Man this pull request has been a godsend this week, it takes 3 minutes to rebuild each image with a new log4shell fix instead of 15-20 minutes. Thank you so much for this.

**Comment by GoliathLabs** [comment]
Since I also use this Docker image on my end, it was very good to have the updates available so quickly. I think that the PR was merged just at the right time. 😄

I am always glad to help and wish you happy holidays.

**Pull request merged**
