### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bruvv**

### CODE REVIEW

**Comment by bruvv** [comment]
@jacobalberty ping

**Comment by bruvv** [comment]
@jacobalberty why is this still not merged?

**Comment by PrplHaz4** [comment]
I think LOTSOFDEVICES should link the the UBNT docs - as I believe there are some potential gotchas/unexpected side effects...

**Comment by jacobalberty** [comment]
I'm going to merge it and add in a link to the doc  for [high number of unifi devices](https://help.ui.com/hc/en-us/articles/115005159588-UniFi-How-to-Tune-the-Network-Application-for-High-Number-of-UniFi-Devices) as well as a listing of the changes it makes

**Pull request merged**
