### PR TITLE
[TASK] bump to 7.5.176

### LINKED ISSUE #683: Update README to list 7.5.174
### Operating system

N/A

### UniFi Tag

latest

### Docker run

N/A

### Bug description

The README's "Current Information" says 7.4.162, but the table farther below shows "latest" as 7.5.174... Which is correct? Thanks for this terrific package!

> ## Current Information
>
> The current "latest" version is Unifi Controller 7.4.162. There are currently no hot-fix or CVE warnings affecting Unifi Controller.

### Steps to reproduce

N/A

### Relevant log output

```shell
N/A
```

### LINKED ISSUE #684: DNS issue after upgraded to v7.5.174
### Operating system

synology DSM 7.1.1-42962 Update 6

### UniFi Tag

latest

### Docker run

docker 

### Bug description

docker run -d --init \
   --restart=unless-stopped \
   -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -p 6789:6789 -p 8843:8843 -p 8880:8880\
   -v ~/docker/unifi:/unifi \
   --user unifi \
   --name unifi \
   jacobalberty/unifi

### Steps to reproduce

My previous unifi version is 7.0.23. When I deleted the container and image in synology, pulled the latest version and launched it, my whole network has DNS issues. Everything is unchanged including the docker folder.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by arkste**
bump to [7.5.176](https://community.ui.com/releases/UniFi-Network-Application-7-5-176/0a224764-0603-4a8b-a038-1a7d59c6615c), which fixes #684 and also fixes #683.

### CODE REVIEW

**Comment by DKeppi** [comment]
@jacobalberty 
I have also an USG and problems with DNS, 7.5.174 was switched back to RC from Unifi because its buggy, new Release Version is 7.5.176...could you pls merge this task!

**Comment by timbuktu234** [comment]
@jacobalberty

Also awaiting version 7.5.176 since it fixes a couple of issues on the controller.

**Comment by jcostom** [comment]
Thanks @arkste for doing this. I was on vacation, and was planning to submit a PR when I got home if it wasn't already done. Good on you for beating me to it!

Also thanks for catching the version thing in the README that I missed on my previous PR for 7.5.174!

**Comment by jdmac87** [comment]
Are there any expectations on when this will be merged?
Will further manual actions be required by the project collaborators to then build and publish the updated docker image to the Docker hub?

**Review by jdmac87 — APPROVED** [review]
Reviewed the code changes and everything looks sensible.
Tested in lab with the changes proposed by the PR and was able to deploy 7.5.176 with ease.

**Comment by jacobalberty** [comment]
Sorry been a busy few months at work. I havent even had a chance to update my own wifi network lately. Pulling this in now and will try to stay on top of it for the 7.5.178 release.

**Review by jacobalberty — APPROVED** [review]
🐿️

**Comment by jdmac87** [comment]
> Sorry been a busy few months at work. I havent even had a chance to update my own wifi network lately. Pulling this in now and will try to stay on top of it for the 7.5.178 release.

Totally appreciate the effort and situation. Thank you.

**Comment by barbatrukko** [comment]
I would update my network controller running in RaspPi4 (allways running on RasPi4/ubuntu) but when i try to pull new image i receive this error

```
root@raspi4unifi:/opt# docker pull jacobalberty/unifi:latest
latest: Pulling from jacobalberty/unifi
no matching manifest for linux/arm/v7 in the manifest list entries
root@raspi4unifi:/opt#

```

**Comment by arkste** [comment]
its not related to this MR, instead #681 / the update to 7.5 has removed `linux/arm/v7` support.

**Comment by barbatrukko** [comment]
> its not related to this MR, instead #681 / the update to 7.5 has removed `linux/arm/v7` support.

This is only for dicker version or also for .deb normal package?
If I install debian on my rasPi4 can install the original package?

**Comment by jdmac87** [comment]
> > its not related to this MR, instead #681 / the update to 7.5 has removed `linux/arm/v7` support.
> 
> This is only for dicker version or also for .deb normal package? If I install debian on my rasPi4 can install the original package?

Unifi itself, I am seeing dropped support for 32-bit OS on RPi.

**Comment by barbatrukko** [comment]
So, if I install 64bit ubuntu... it will work again?
Pi4 support 64 bit OS

**Comment by jdmac87** [comment]
> So, if I install 64bit ubuntu... it will work again? Pi4 support 64 bit OS

According to articles I have seen, yes.

https://reddit.com/r/Ubiquiti/s/z1HIrJILyg

**Pull request merged**
