### PR TITLE
[DOC] Add tutorial on how to fix permissions issues that cause backup…

### PR DESCRIPTION
**Pull request by mountaindude**
… downloads to fail.

Use a prefix like [TASK], [BUGFIX], [DOC] or [CGL] and provide a general summary of your changes in the Title above.

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

*Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.*

Please provide enough information so that others can review your pull request:

## Description
Explain the **details** for making this change. What existing problem does the pull request solve?

## Motivation and Context
Why is this change required? What problem does it solve?

## How Has This Been Tested?

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

## Closing issues

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

## Checklist:
Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!
- [ ] My code follows the code style of this project. (CI will test it anyway and also needs approval)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mountaindude** [comment]
Relating to issue #512.

**Comment by mountaindude** [comment]
Ah - forgot to add a link from the repo's main README to the new file. 
Feel free to add it - you know that file best anyway :)

**Comment by sam9032** [comment]
Thank you! Got the same problem today and found the issue and this readme :rocket:

**Comment by koitsu** [comment]
The core complexity here is using `docker run --user unifi` (but via Docker Compose); you will find several things break because of this (as described in this document).

I am very, very surprised the author did not consider using `chmod 1777` on the `backups` directory, rather than having to create a UID/GID on the host that maps to the same UID/GID on the guest (Docker).  The sticky bit makes it so that only the proper owner or person in a group can remove files from the directory.  `chmod 777` would also work, but then any user can `rm` files from that directory (777 is generally shunned on a multi-user system).  Please do some research on the sticky bit if you aren't familiar with it.

This setup can be done *in advance* of running the controller for the first time, i.e. `mkdir -m 1777 -p ~/your/unifi/volume/mount/path/data/backup`, or post-run.

On the flip side, if you **do not** run the Docker container with `--user unifi` and let it run as root (default), things will work fine (for UniFi backups and everything else).  However, you've now exchanged one problem for another: on the **host** side you'll have files owned by root which you can't read/access: particularly, most (but not all!) of the files in `data/db` (MongoDB) will be owned `root:root` with perms `0600`.  This makes it hard to do **backups of the host itself** (I'm not talking about UniFi Controller backups, I'm talking about full-fledged Linux host backups) unless your backup script is running as root on the host.

This latter situation is the one I deal with.

In the latter case, I strongly suspect the problem relates to MongoDB being stupid and not honouring umask.  I've never verified this -- call it "gut sysadmin intuition" -- but I just looked it up and sure enough we have our answer: https://docs.mongodb.com/manual/reference/parameters/#mongodb-parameter-param.honorSystemUmask and https://docs.mongodb.com/manual/reference/parameters/#mongodb-parameter-param.processUmask

Therefore, for the latter situation (and thus the default of not running the Docker container with `--user unifi`), I strongly suggest figuring out how to somehow automate doing `mongod --setParameter processUmask=022` so that all its files end with perms 644 (i.e. `-rw-r--r--`), and all its directories end up being 755 (i.e. `drwxr-xr-x`). @jacobalberty If you're able to figure out how to accomplish that, that would be awesome. Sadly, this can't be something pushed onto Ubiquiti. Let me know if you figure it out; push a unique tag to DockerHub and I can try it out/verify for you, if that's easier.

Footnote: it never ceases to amaze me how software today seems to forget about all of this.  It's like those of us who are old UNIX systems administrators have to keep coming out of the woodwork to explain to present-day software people (MongoDB, Docker, etc. and users of these softwares) file permissions and things that have never changed in the past 50 years of UNIX. :)

**Comment by jacobalberty** [comment]
@koitsu  I'm probably going to be taking a different path to fixing perms for the long run. I'm working on a small setuid binary that will take a hardcoded path to change ownership of the path to the calling user. So the binary can run on start and it auto change all of /unifi to be owned by whatever user the container is run by

**Comment by koitsu** [comment]
@jacobalberty I'm not sure how that solves the problem I describe; users of your image would have to stop and restart the container regularly.  MongoDB manages its database files during run-time; its `.wt` files (amongst many others) get deleted, renamed, rotated, whenever it wants.  Since MongoDB runs as user root in the container (default, unless using `docker run --user`, new files will effectively be owned by `root:root` and thus not necessarily accessible to a user *on the host*.  It depends on if the MongoDB database files are globally readable or not -- hence the umask aspect I speak of.

I have a lot more to say about all of this, but in honour of brevity, I'd suggest adding `RUN mkdir -p /unifi/data/backup && chmod 1777 /unifi/data/backup` line to the Dockerfile, or work it into one of the existing `RUN` lines you already have.  That should solve the problem universally, regardless if using `--user` or not.  Also, mkdir's `-p` flag will always result in exit code 0 even on directories that already exist, saving you from `&&` and `||` shell logic pains.

Regarding MongoDB's brain-damaged operation of not having `honorSystemUmask=true` as a default: I read a little bit about this.  There are 3 different ways to enable this, but the best way (IMO) is to tweak the Mongo server config file, since its read on start-up before the daemon has a chance to do anything.  Ubiquiti is using MongoDB version 3.6.3, which does offer the umask setting in question.  However, the MongoDB config in the container, `/etc/mongodb.conf`, is the MongoDB 2.x legacy key=value file format ([which is still supported](https://docs.mongodb.com/v3.6/reference/configuration-options/)), not YAML like in 3.x or newer.  I don't know how to achieve setting the `honorSystemUmask` [server parameter](https://docs.mongodb.com/v3.6/reference/parameters/) using that legacy file format.

**Comment by koitsu** [comment]
I've submit Issue #516 along with a PR that should hopefully address what the OP here has cited, without need for a long document.  :)

**Comment by koitsu** [comment]
Actually, sorry about this -- it looks like #516 is not correct and not a viable solution. I didn't realise that the useradd/groupadd were being done via `RUN` (i.e. during image build-time) and not during actual container launch-time.

**Comment by jacobalberty** [comment]
mongodb doesn't run as root unless unifi is running as root, that's not the core of the issue. mongodb is launched by unifi so it's running as whatever unifi is running as. the core of  the issue is that the folders in question may be owned by a user other than the one running inside the container. So I'm toying around with adding [permset](https://github.com/jacobalberty/permset) to the container. I need to sit on my hands for a bit and think about possible security issues with that approach and possibly add some additional logging of which files/folders did end up needing to be chowned.

**Pull request merged**
