### PR TITLE
updating to 8.1.127

### PR DESCRIPTION
**Pull request by dcarbone**
Bumping build to 8.1.127, using go 1.22 base image.

### CODE REVIEW

**Comment by Sysadminfromhell** [comment]
When this PR is going to be approved, merged and built on docker hub?

**Comment by dcarbone** [comment]
Until it has, I've built and pushed this PR here: https://hub.docker.com/r/dancarbone/jacobalberty-unifi/tags

**Comment by jpvj** [comment]
Hi Daniel,

Thank you for your work helpin Jacob getting the latest versions out - much appreciated!

Cheers!

/JP

**Comment by alepouna** [comment]
Hey just checking in, unless I am missing something, tag v8.1.127 seems to be published? https://hub.docker.com/layers/dancarbone/jacobalberty-unifi/v8.1.127/images/sha256-583e57270e71a3f3483fb213d4f535c55ea50fc201b9df01806e6897c4906239?context=explore

**Comment by davecarlson** [comment]
is this repo still maintained ?

**Comment by jpvj** [comment]
> is this repo still maintained ?

Good question ;-)

It seems Jacob is not so active anymore:
https://github.com/jacobalberty

Personally I just installed via the link provided by dcarbone - no issues so far.

**Comment by ogghi** [comment]
The question is, if there will be updates in the future?

**Comment by davecarlson** [comment]
> The question is, if there will be updates in the future?
Yup, if not, be good to add extra maintainers just as dcarbone) to the project.

**Comment by flinty32** [comment]
Is the Projekt Dead?  
On Webseite Ubiquitti  has released UniFi Network Application 8.2.93

**Comment by flinty32** [comment]
> Until it has, I've built and pushed this PR here: https://hub.docker.com/r/dancarbone/jacobalberty-unifi/tags

ok, Can you Update to the new one: UniFi Network Application 8.2.93 ? 
Is now released.

**Comment by dcarbone** [comment]
superseded by #745

**Pull request closed without merging**
