### PR TITLE
Added DHCP server port

### PR DESCRIPTION
**Pull request by Luzifer**
This enables the image to act as a DHCP server on the host in order to support the "DHCP Server" option in site networking of the Unifi controller.

fixes jacobalberty/unifi-docker#3

### CODE REVIEW

**Comment by hemsleyk** [comment]
Is this tested? The documentation says that the hardware USG is what DHCP runs off of. Also Docker is purely layer 3, AFAIK DHCP wouldn't even work.

**Comment by jacobalberty** [comment]
I havent had a chance to test it but I simply run --net=host dhcp and the like then work from docker containers

**Comment by hemsleyk** [comment]
I just know that the web UI as of version 5 requires a USG to turn on DHCP. I don't think this was ever a feature of the controller itself. Or if it was they decommissioned it a long time ago.

**Comment by Luzifer** [comment]
Yeah, the option for DHCP was shown in the controller in v4 and is not longer available…

**Pull request closed without merging**
