### PR TITLE
Move backup folder locally

### PR DESCRIPTION
**Pull request by ThomDietrich**
Hey guys,
I would argue that it's a meaningful default to mount the backup (and therefore autobackup) folder from a local subfolder. These files are clearly of exchange nature for the emergency case and hence should be bundled with `docker-compose.yml`.

Happy to revert to a comment or a mentioning of this option in the README.

Wdyt?

### CODE REVIEW

**Comment by ThomDietrich** [comment]
Please discuss.

**Comment by ThomDietrich** [comment]
Hey all,
since there was no feedback I assume you are reluctant to make this change. I've changed it to be commented out by default. Is this a good compromise? I would vote to just make this a default, it offers a clear improvement to the enduser.

**Comment by ThomDietrich** [comment]
@jacobalberty almost one year has passed. I would be thankful if we could start a discussion and merge this PR soon.

**Comment by ThomDietrich** [comment]
@jacobalberty is there any reason not to merge this?

**Comment by martinvw** [comment]
I would also like this because now I fetch the backups directly from the docker data folder which feels sub-optimal :-)

**Pull request merged**
