### PR TITLE
Bump controller to 8.2.93

### PR DESCRIPTION
**Pull request by dcarbone**

### CODE REVIEW

**Comment by jpvj** [comment]
Thank you dcarbone for pushing 8.2.93 to Docker Hub - much appreciated!

**Review by Bigjoke007 — APPROVED** [review]

**Review by waja — APPROVED** [review]

**Review by kenayagi — APPROVED** [review]

**Review by MrStrong — APPROVED** [review]

**Comment by Vest** [comment]
Dear Sirs,

I am curious, will anybody accept this PR?
I didn't want to bother you much ^_^

Thanks

**Comment by freddyw** [comment]
> Dear Sirs,
> 
> I am curious, will anybody accept this PR? I didn't want to bother you much ^_^
> 
> Thanks

Very curious about this as well. Would love to try out the new features of 8.2.93!!

**Comment by dcarbone** [comment]
Until accepted, I've built and pushed this version to my dockerhub account:

https://hub.docker.com/r/dancarbone/jacobalberty-unifi/tags

**Comment by waja** [comment]
> Until accepted, I've built and pushed this version to my dockerhub account:
> 
> https://hub.docker.com/r/dancarbone/jacobalberty-unifi/tags

Feel free to also use https://github.com/users/waja/packages/container/package/unifi :)

**Comment by cpauls** [comment]
> > Until accepted, I've built and pushed this version to my dockerhub account:
> > https://hub.docker.com/r/dancarbone/jacobalberty-unifi/tags
> 
> Feel free to also use https://github.com/users/waja/packages/container/package/unifi :)

Hi @waja, 
do you mean 8.2.93? Currently 8.2.39 is tagged: https://github.com/waja/docker-unifi/pkgs/container/unifi/225751716?tag=v8.2.39

**Comment by waja** [comment]
> do you mean 8.2.93?

Hi @cpauls, indeed you are true. Started a new pipeline for building the correct tag, but should not differ from `v8.2` or `latest`.

**Comment by drwtsn32x** [comment]
Thank you @jacobalberty !!

**Comment by freddyw** [comment]
Works like a charm, thank you @dcarbone and @jacobalberty !

**Pull request merged**
