### PR TITLE
bump stable to 5.13.29 & upgrade to mongo 3.6

### PR DESCRIPTION
**Pull request by rohanrns**
Minimal testing of the upgrade of mongo 3.6. It passes a basic smoke test and the controller starts and does things. But I'd love some other people to poke at it before merging this.

### CODE REVIEW

**Comment by hardoverflow** [comment]
I can confirm that everything is great! Can be merged into master.

**Comment by iogitio** [comment]
hoping for a merge soon, good features in this latest update

**Comment by IngmarStein** [comment]
If you bump the docker-compose to version 2.3, why not go straight to 2.4?

**Comment by buckaroogeek** [comment]
I use version 2.4 in my docker-compose.yaml file for unifi controller without issue.

**Comment by IngmarStein** [comment]
For the impatient: I've uploaded an image using this version on Docker Hub: `ingmarstein/unifi:5.13.29`. I'm planning to keep this around only until the official version is up.

**Comment by jacobalberty** [comment]
Hey. I'm going to try to get to merging this today or tonight. Last time I tried to bump mongo versions (to a version that was still compatible with unifi) I ran into a few issues so I want to test against my systems before I do a full merge and just haven't had a chance to sit down for it.

**Comment by sabbene** [comment]
I have been running @rohanrns's fork since Friday, so far so good.

**Comment by jacobalberty** [comment]
Should be merged in now. It build cleanly on the arm32v7-cross branch so hopefully it runs there as well.

**Pull request merged**
